
http://localhost:3000/api/member

###

http://localhost:3000/api/member/count

###

http://localhost:3000/api/member/5b70ca1b9031ed00c046a903

###

POST http://localhost:3000/api/member/add
content-type: application/json

{
    "name": "RestUser2"
}

###

PUT http://localhost:3000/api/member/5b70ca1b9031ed00c046a903
content-type: application/json

{
    "name": "RestUser"
}